//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCrafts.App.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCrafts.App.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day: .
        /// </summary>
        public static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details:.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yy.
        /// </summary>
        public static string FormatDateMonthDayYear {
            get {
                return ResourceManager.GetString("FormatDateMonthDayYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string FormatHourMinute {
            get {
                return ResourceManager.GetString("FormatHourMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string HoursSeparator {
            get {
                return ResourceManager.GetString("HoursSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours: .
        /// </summary>
        public static string HourText {
            get {
                return ResourceManager.GetString("HourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date not found.
        /// </summary>
        public static string NoDate {
            get {
                return ResourceManager.GetString("NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker not found.
        /// </summary>
        public static string NoSpeaker {
            get {
                return ResourceManager.GetString("NoSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not found.
        /// </summary>
        public static string NoTag {
            get {
                return ResourceManager.GetString("NoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers:.
        /// </summary>
        public static string SpeakersHeader {
            get {
                return ResourceManager.GetString("SpeakersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string TagSeparator {
            get {
                return ResourceManager.GetString("TagSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags: .
        /// </summary>
        public static string TagsText {
            get {
                return ResourceManager.GetString("TagsText", resourceCulture);
            }
        }
    }
}
