#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NCrafts.App.Droid.Resource", IsApplication=true)]

namespace NCrafts.App.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::NCrafts.App.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abouticon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int clockicon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dailyicon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iconxamarin = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mapicon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int personalscheduleicon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int profilpicture = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int profilpictureicon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sessionsicon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int shareicon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int simonbrown = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int simonbrown50 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int simonbrown75 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int speakersicon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int splashscreen = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int viseoicon = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030001
			public const int MyTheme = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int MyTheme_Base = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int MyTheme_Splash = 2130903042;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
